services:
  client:
    image: fabriciolopes1325/clinica_client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: clinica_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env


  server:
    image: fabriciolopes1325/clinica_server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: clinica_server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: clinica_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      retries: 10
      interval: 15s

volumes:
  dbdata:
